### ISSUE TITLE
Research on IML

### ISSUE THREAD

**Issue by gramyareddy** [dasarisasidhar/Automate-ML-Modeling#3]
1. Find more add-ons to IML

**Comment by dasarisasidhar** [comment]
completed for regression need to integrate for final version

**Comment by dasarisasidhar** [comment]
if we implement for all models it is some what messy. shell we implement for top 3 models or we will ask the user to select  @gramyareddy

**Comment by gramyareddy** [comment]
Partialy completed research on IML.
Have to implement this for classification and find if more info could be drawn from this

**Comment by dasarisasidhar** [comment]
will implement only if the model performs betters and it is compatible for IML
